export interface definir_configuracoes_iniciais_documento {
    definir_configuracoes_iniciais_documento_id: string,
    calcular_lucro_bruto: string,
    observacoes_documento_compreendem: string,
    para_ema_EP_vendas_documentos: string,
    resposta_liberacao_entrada_estoque_abaixo_nivel: string,
    bloquear_estoque_negativo: string,
    bloquear_estoque_negativo_por: string,
    metodo_arredondamento: string,
    data_base_taxa_cambio: string,
    arredondar_valor_imposto_linhas: string,
    exibir_observacao_arredondamento: string,
    bloquear_documentos_data_lancamento: string,
    permitir_data_lancamento_futuro: string,
    selected?: boolean,
}