export interface despesas_Adicionais {
    despesas_Adicionaisid: string,
    nome_despesa: string,
    conta_receita: string,
    conta_despesa: string,
    valor_fixo_receitas: 0,
    valor_fixo_despesas: 0,
    sujetio_irf: string,
    metodo_distribuicao: string,
    metodo_transferencia: string,
    estoque: string,
    ultimo_preco_compra: string,
    tipo_despesas_adicionais: string,
    selected: boolean,
}